version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /conf/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword
    volumes:
      - ./redis.conf:/conf/redis.conf
