version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /conf/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword
    volumes:
      - ./redis.conf:/conf/redis.conf
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
